spring:
  application:
    name: simple
  security:
    user:
      name: root
      password: root
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: Deepak@1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: INFO

  file:
    name: logs/myapp.log       
    max-size: 10MB             
    max-history: 30   

# server:
#   port: 8888

# server:
#   tomcat:
#     keep-alive-timeout: 20s  # 20 seconds

